apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: team13
  name: team13-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["networking.istio.io"]
    resources: ["virtualservices"]
    verbs: ["get", "list", "create", "update"]
