apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: team13app
  namespace: team13
spec:
  hosts:
    - "*"
  gateways:
    - team13-gateway
  http:
    - match:
        - headers:
            user-agent:
              regex: ".*Chrome.*"
      rewrite:
        uri: /index-chrome.html
      route:
        - destination:
            host: team13-webpage
            port:
              number: 80
    - match:
        - headers:
            user-agent:
              regex: ".*Firefox.*"
      rewrite:
        uri: /index-firefox.html
      route:
        - destination:
            host: team13-webpage
            port:
              number: 80
